# Site settings
title: Smit Joshi - Portfolio
description: Full Stack Java Developer | Microservices | Spring Boot | Hibernate | Flutter | RESTful Services
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Smit Joshi
user_description: Passionate Postgrad ğŸ“student with Strong academics ğŸ”. Expert in Java, Spring Boot, Flutter, Spring Security. Dedicated backend developer ğŸ’». Let's code the future!ğŸš€
user_title: Software Developer
# email: anon@anon.com
# twitter_username: lorem_ipsum
github_username:  smit-joshi814
# gplus_username:  lorem_ipsum
linkedin_username: smit-joshi814

icon_size: 75px

# Google-analytics
google-analytics:
  id: ""


exclude: ['package.json', 'src' , 'node_modules']
